[project]
name = "drive-clone"
revision = "1.0"

# Extend configurations from subdirectories
# extends = [ "subdir1", "subdir2" ]

[profiles.default]
DATABASE_URL = { description = "Database connection string", required = true }
DATABASE_URL_POOLED = { description = "Database connection string for pooled queries", required = true }
NEON_AUTH_BASE_URL = { description = "Base URL for Neon Auth", required = true }
NEON_AUTH_COOKIE_SECRET = { description = "Cookie secret for Neon Auth", required = true }
LOG_LEVEL = { description = "Log level for logger", default = "WARN" }
NEXT_TELEMETRY_DISABLED = { description= "Disable next cli's tools telemetry", default = "1" }
IGNORE_BUILD_ERRORS = { description = "Ignore build errors as this shall be caught by CI", default = "true" }

[scopes.drizzle]
secrets = ["DATABASE_URL", "DATABASE_URL_POOLED"]

# [profiles.development]
# Development profile inherits all secrets from default profile
# Only define secrets here that need different values or settings than default
# DATABASE_URL = { default = "sqlite:///dev.db" }
#
# New secrets
# REDIS_URL = { description = "Redis connection URL for caching", required = false, default = "redis://localhost:6379" }